version: "3.8"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "3000:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: always
  ragembedding:
    container_name: HuggingFaceEmbedding
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.6
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
    command:
      - --model-id
      - BAAI/bge-large-en-v1.5
      - --revision
      - refs/pr/5
    restart: always
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - ./Qdrant:/qdrant/storage
  chatapi:
    container_name: dotnetapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Production"  
    ports:
      - 8000:80
      - 3255:8080
    depends_on:
      - qdrant
      - ragembedding
      - ollama
    restart: always
#Move Toward a Public API only format
#  nginx:
#    container_name: nginx
#    image: nginx:stable-alpine
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro #/etc/nginx/nginx.conf
#      - ./nginx/ssl:/etc/nginx/ssl  # Mount the directory containing your SSL file
#    ports:
#      - 443:443
#    restart: always   
#    depends_on:
#      - hindalcobot
